### ISSUE TITLE
Cannot be opened in Order Shipments of 2.4.3

### ISSUE THREAD

**Issue by tuigougou** [vijayrami/Magelearn_Salesorder#1]
This is a very useful plug-in, I am very happy to find and use it, but after testing it does not work properly in version 2.4.3. If you can update, thank you very much for your contribution.

**Comment by vijayrami** [comment]
Ok. I will check in magento version 2.4.3 and will let you know.

**Comment by tuigougou** [comment]
Thank you very much for your prompt reply. The current known problem is that Items Ordered can display product images normally, but Invoices and Order Shipments cannot be opened.

**Comment by tuigougou** [comment]
Hello, is there any progress?

**Comment by vijayrami** [comment]
OK..i got the issue.
it is due to https://magento.stackexchange.com/questions/289853/uncaught-exception-typeerror-imagebuildersetproduct-must-be-an-instance-o
Will solve soon.

**Comment by vijayrami** [comment]
Hello,
I have updated code.
It is solved now.

**Comment by tuigougou** [comment]
This feature is really a great creation, thank you for your great contribution.
